######################################################################
# Automatically generated by qmake (3.0) lun. nov. 2 08:59:10 2015
######################################################################

TEMPLATE = app
TARGET = 20_bugs
INCLUDEPATH += .

# Input
SOURCES += bugs.cpp
QMAKE_CXXFLAGS += -std=c++11
